### ISSUE TITLE
IOError: [Errno 22] invalid mode ('wb') or filename: u'010m\\bin\\3.KEY*'

### ISSUE THREAD

**Issue by TanatOSz** [System25/drxtract#4]
```
D:\drxtract>drxtract mac facep.dir facep
Traceback (most recent call last):
  File "D:\drxtract\riffxtract.py", line 329, in <module>
    parse_riff(fileContent, rifx_offset)
  File "D:\drxtract\riffxtract.py", line 246, in parse_riff
    parse_mmap(block_data, fileContent, offset)
  File "D:\drxtract\riffxtract.py", line 161, in parse_mmap
    with open(os.path.join(sys.argv[3], BINDIR, file_name), 'wb') as file:
IOError: [Errno 22] invalid mode ('wb') or filename: u'facep\\bin\\3.KEY*'
ERROR:root:Can not find a VWLB file!
ERROR:root:Can not find a KEY* file!
ERROR:root:Can not find a VWSC file!
```

[FACEP.ZIP](https://github.com/System25/drxtract/files/4001894/FACEP.ZIP)

**Comment by System25** [comment]
It seems that Windows does not support "\*" in the file name, and a "3.KEY*" file can not be created on Windows.
There are some files that have "*" or spaces in the file extension. In Linux there is no problem with that by I suppose that Windows won't allow it.

I'll check the code to try to remove those characters from the file extensions.

Best regards!

**Comment by System25** [comment]
OK. Just checked Windows OS compatibilty. Now it may work.
But keep in mind that this project is a WIP.
Now I'm working of extracting images with different color maps, so no image extraction at this moment.
Best regards!

**Comment by TanatOSz** [comment]
I'm solve it, but here is another trouble
```
D:\drxtract>drxtract mac facep.dir facep
INFO:root:Director version: dir4
INFO:root:There is 8 elements in the casting!
INFO:root:Casting element number 1 is 36.CASt file!
INFO:root:facep\bin\36.CASt: is a image file
INFO:root:Casting element number 2 is 39.CASt file!
INFO:root:facep\bin\39.CASt: is a image file
INFO:root:Casting element number 3 is 25.CASt file!
INFO:root:facep\bin\25.CASt: is a image file
INFO:root:Casting element number 4 is 27.CASt file!
INFO:root:facep\bin\27.CASt: is a script reference file
INFO:root:facep\bin\27.CASt: has no related data!
INFO:root:Casting element number 5 is 28.CASt file!
INFO:root:facep\bin\28.CASt: is a script reference file
INFO:root:facep\bin\28.CASt: has no related data!
INFO:root:Casting element number 6 is 29.CASt file!
INFO:root:facep\bin\29.CASt: is a script reference file
INFO:root:facep\bin\29.CASt: has no related data!
INFO:root:Casting element number 7 is 50.CASt file!
WARNING:root:facep\bin\50.CASt: data_type unknown (4)!
Traceback (most recent call last):
  File "D:\drxtract\casxtract.py", line 922, in <module>
    lctx_elements, os.path.join(sys.argv[2], BINDIR, lnam_file))
  File "D:\drxtract\casxtract.py", line 765, in parse_cast_file
    jsfile.write(json.dumps(castData, indent=4, sort_keys=True))
  File "C:\Python27\lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\Python27\lib\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\Python27\lib\json\encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x83 in position 0: invalid start byte
```
Your script check japanese only in the file name?

**Comment by TanatOSz** [comment]
Thanks.
